// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSPLxWQlJoJ8BJrmdq72q1-0PDTRPXBY',
    appId: '1:288384663513:web:a31b9bb93b63383e8a23c8',
    messagingSenderId: '288384663513',
    projectId: 'e-commerce-bc2e7',
    authDomain: 'e-commerce-bc2e7.firebaseapp.com',
    storageBucket: 'e-commerce-bc2e7.appspot.com',
    measurementId: 'G-RRHPQP2871',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAngTcwOZdFuymE52ufssZCN2GUh15_qY',
    appId: '1:288384663513:android:6ce0182a046833138a23c8',
    messagingSenderId: '288384663513',
    projectId: 'e-commerce-bc2e7',
    storageBucket: 'e-commerce-bc2e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQWOq2XyXCGL-M6WD_8l4cv1kQQu_pte4',
    appId: '1:288384663513:ios:23cfafc2826e10ab8a23c8',
    messagingSenderId: '288384663513',
    projectId: 'e-commerce-bc2e7',
    storageBucket: 'e-commerce-bc2e7.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQWOq2XyXCGL-M6WD_8l4cv1kQQu_pte4',
    appId: '1:288384663513:ios:23cfafc2826e10ab8a23c8',
    messagingSenderId: '288384663513',
    projectId: 'e-commerce-bc2e7',
    storageBucket: 'e-commerce-bc2e7.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgSPLxWQlJoJ8BJrmdq72q1-0PDTRPXBY',
    appId: '1:288384663513:web:a8bf09bf532535868a23c8',
    messagingSenderId: '288384663513',
    projectId: 'e-commerce-bc2e7',
    authDomain: 'e-commerce-bc2e7.firebaseapp.com',
    storageBucket: 'e-commerce-bc2e7.appspot.com',
    measurementId: 'G-S98DR552LV',
  );
}
